In [6]:
import numpy as np
from pandas import DataFrame
from glob import glob

files = glob('comparison/*.txt')

dat = []
for f in files:
    try:
        with open(f) as fh:
            lines = [l.strip() for l in fh.readlines()]
        d = {}

        name_parts = f.split('/')[1].split('.')[0].split('_')
        if len(name_parts) == 5:
            bbone = name_parts[1] + '_360'
        else:
            bbone = name_parts[1]
        det = name_parts[2]
        bs = int(name_parts[-1].split('=')[1])
        d['bbone'] = bbone
        d['det'] = det
        d['bs'] = bs

        ts = []
        for l in lines:
            try:
                t = float(l)
                ts.append(t)

            except ValueError:
                ps = l.split(' ')
                d[ps[0][:-1]] = float(ps[1][:-1])


        d['tfirst'] = ts[0]    
        d['tmean'] = np.mean(ts[1:])
        d['t/sample'] = np.mean(ts[1:]) / bs
        d['ts'] = ts
        d['f'] = f

        dat.append(d)
    except Exception as e:
        print('ERROR', e)
        print(f)
        print('\t', l)
        
df = DataFrame(dat)
df.sort_values(['bbone', 'det', 'bs'])

ERROR list index out of range
comparison/metrabs_rn152_y4_bs=128.txt
	 load: 50.30s

,bbone,det,bs,load,full_time,tfirst,tmean,t/sample,ts,f
18,eff2l,y4,8,73.74,108.03,31397.864103,279.742171,34.967771,"[31397.864103, 250.721216, 297.269821, 322.669...",comparison/metrabs_eff2l_y4_bs=8.txt
25,eff2l,y4,16,73.74,75.50,466.055393,480.874956,30.054685,"[466.055393, 546.171904, 491.705179, 465.95501...",comparison/metrabs_eff2l_y4_bs=16.txt
13,eff2l,y4,32,79.21,82.64,938.287020,885.897597,27.684300,"[938.28702, 902.963877, 871.189594, 874.304533...",comparison/metrabs_eff2l_y4_bs=32.txt
45,eff2l,y4,64,79.21,93.92,1853.033066,1801.763853,28.152560,"[1853.033066, 1732.906342, 1776.235819, 1896.1...",comparison/metrabs_eff2l_y4_bs=64.txt
50,eff2l,y4,128,79.21,129.32,36806.452274,3976.914167,31.069642,"[36806.452274, 3976.914167]",comparison/metrabs_eff2l_y4_bs=128.txt
58,eff2l_360,y4,8,67.72,102.14,29740.103722,293.707550,36.713444,"[29740.103722, 310.539246, 374.058008, 355.492...",comparison/metrabs_eff2l_y4_360_bs=8.txt
14,eff2l_360,y4,16,67.72,73.92,444.922447,493.194322,30.824645,"[444.922447, 538.204908, 496.591568, 463.24157...",comparison/metrabs_eff2l_y4_360_bs=16.txt
34,eff2l_360,y4,32,70.20,85.18,955.171824,910.686851,28.458964,"[955.171824, 892.01355, 909.067869, 918.698072...",comparison/metrabs_eff2l_y4_360_bs=32.txt
32,eff2l_360,y4,64,70.20,90.43,1857.242584,1856.952031,29.014875,"[1857.242584, 1802.392006, 1844.459772, 1924.0...",comparison/metrabs_eff2l_y4_360_bs=64.txt
30,eff2l_360,y4,128,70.20,121.25,33749.481916,4055.341005,31.682352,"[33749.481916, 4055.341005]",comparison/metrabs_eff2l_y4_360_bs=128.txt
0,eff2m,y4,8,69.28,102.92,22930.008888,345.508913,43.188614,"[22930.008888, 250.952482, 264.338017, 2974.69...",comparison/metrabs_eff2m_y4_bs=8.txt
52,eff2m,y4,16,69.28,73.59,371.381044,391.835312,24.489707,"[371.381044, 444.94772, 361.650467, 370.144129...",comparison/metrabs_eff2m_y4_bs=16.txt
8,eff2m,y4,32,75.41,79.76,804.205656,717.960358,22.436261,"[804.205656, 706.303835, 730.765581, 709.36656...",comparison/metrabs_eff2m_y4_bs=32.txt
33,eff2m,y4,64,75.41,90.09,1455.455542,1485.783656,23.215370,"[1455.455542, 1416.662216, 1532.461882, 1508.2...",comparison/metrabs_eff2m_y4_bs=64.txt
35,eff2m,y4,128,75.41,115.63,23679.089069,3401.269197,26.572416,"[23679.089069, 3401.269197]",comparison/metrabs_eff2m_y4_bs=128.txt
40,eff2s,y4,8,37.01,87.53,17234.220266,208.428105,26.053513,"[17234.220266, 232.420683, 258.033276, 222.673...",comparison/metrabs_eff2s_y4_bs=8.txt
21,eff2s,y4,16,37.01,70.84,444.418430,341.078957,21.317435,"[444.41843, 367.215157, 316.669226, 326.079845...",comparison/metrabs_eff2s_y4_bs=16.txt
36,eff2s,y4,32,42.79,77.82,863.946438,642.543554,20.079486,"[863.946438, 623.897314, 666.402578, 659.16395...",comparison/metrabs_eff2s_y4_bs=32.txt
2,eff2s,y4,64,42.79,89.46,1614.689112,1343.519767,20.992496,"[1614.689112, 1337.541103, 1357.389212, 1335.6...",comparison/metrabs_eff2s_y4_bs=64.txt
10,eff2s,y4,128,42.79,113.12,26511.613131,2976.254702,23.251990,"[26511.613131, 2976.254702]",comparison/metrabs_eff2s_y4_bs=128.txt
16,mob3l,y4,8,32.06,86.01,19962.749243,165.934513,20.741814,"[19962.749243, 156.371593, 164.242983, 187.439...",comparison/metrabs_mob3l_y4_bs=8.txt
15,mob3l,y4,16,32.06,81.02,244.837046,260.801832,16.300114,"[244.837046, 284.328938, 250.62871, 255.700111...",comparison/metrabs_mob3l_y4_bs=16.txt
56,mob3l,y4,32,27.17,79.88,597.453833,498.049259,15.564039,"[597.453833, 507.04217, 494.743586, 475.706577...",comparison/metrabs_mob3l_y4_bs=32.txt
23,mob3l,y4,64,27.17,91.02,1159.917593,1111.799638,17.371869,"[1159.917593, 1115.567446, 1111.489773, 1108.3...",comparison/metrabs_mob3l_y4_bs=64.txt
38,mob3l,y4,128,27.17,118.33,22417.672396,2577.085733,20.133482,"[22417.672396, 2577.085733]",comparison/metrabs_mob3l_y4_bs=128.txt
57,mob3l,y4t,8,21.03,72.27,9644.417524,131.206552,16.400819,"[9644.417524, 143.38398, 98.924875, 170.070171...",comparison/metrabs_mob3l_y4t_bs=8.txt
1,mob3l,y4t,16,21.03,66.23,190.435410,169.225097,10.576569,"[190.43541, 144.619703, 136.396885, 196.603298...",comparison/metrabs_mob3l_y4t_bs=16.txt
51,mob3l,y4t,32,21.61,71.97,392.978191,350.229661,10.944677,"[392.978191, 339.224577, 312.961817, 338.37175...",comparison/metrabs_mob3l_y4t_bs=32.txt
31,mob3l,y4t,64,21.61,82.26,676.509142,717.933416,11.217710,"[676.509142, 724.836349, 781.007051, 647.956848]",comparison/metrabs_mob3l_y4t_bs=64.txt
9,mob3l,y4t,128,21.61,90.92,11668.841124,1856.069803,14.500545,"[11668.841124, 1856.069803]",comparison/metrabs_mob3l_y4t_bs=128.txt
55,mob3s,y4,8,23.70,99.66,22361.509562,158.678700,19.834838,"[22361.509562, 154.779911, 156.573534, 181.607...",comparison/metrabs_mob3s_y4_bs=8.txt
48,mob3s,y4,16,23.70,76.41,253.108263,260.369281,16.273080,"[253.108263, 288.667917, 259.917498, 246.80042...",comparison/metrabs_mob3s_y4_bs=16.txt
29,mob3s,y4,32,23.70,81.05,510.250807,498.528918,15.579029,"[510.250807, 507.331133, 499.20249, 502.937794...",comparison/metrabs_mob3s_y4_bs=32.txt
19,mob3s,y4t,8,15.84,82.27,14242.677212,124.187797,15.523475,"[14242.677212, 148.288012, 110.644341, 151.876...",comparison/metrabs_mob3s_y4t_bs=8.txt
44,mob3s,y4t,16,15.84,60.38,160.615683,173.929234,10.870577,"[160.615683, 136.193752, 159.239054, 183.83789...",comparison/metrabs_mob3s_y4t_bs=16.txt
11,mob3s,y4t,32,15.74,73.80,333.281279,337.936083,10.560503,"[333.281279, 314.754486, 344.064951, 368.58129...",comparison/metrabs_mob3s_y4t_bs=32.txt
4,mob3s,y4t,64,15.74,83.16,606.982946,718.153159,11.221143,"[606.982946, 725.635052, 768.170834, 660.653591]",comparison/metrabs_mob3s_y4t_bs=64.txt
39,mob3s,y4t,128,15.74,100.41,16325.945377,1875.851393,14.655089,"[16325.945377, 1875.851393]",comparison/metrabs_mob3s_y4t_bs=128.txt
41,rn101,y4,8,42.32,94.27,23748.034954,220.170309,27.521289,"[23748.034954, 272.896767, 291.07666, 241.7268...",comparison/metrabs_rn101_y4_bs=8.txt
47,rn101,y4,16,42.32,73.14,315.593243,354.648153,22.165510,"[315.593243, 385.579109, 332.222939, 338.80305...",comparison/metrabs_rn101_y4_bs=16.txt
43,rn101,y4,32,41.79,79.59,724.288464,651.061654,20.345677,"[724.288464, 624.796391, 672.827959, 655.23433...",comparison/metrabs_rn101_y4_bs=32.txt
5,rn101,y4,64,41.79,89.47,1337.072849,1321.074645,20.641791,"[1337.072849, 1324.495316, 1331.248045, 1307.4...",comparison/metrabs_rn101_y4_bs=64.txt
37,rn101,y4,128,41.79,113.91,27209.603071,3061.641932,23.919078,"[27209.603071, 3061.641932]",comparison/metrabs_rn101_y4_bs=128.txt
28,rn152,y4,8,54.83,106.07,30717.841387,225.732436,28.216554,"[30717.841387, 216.0182, 218.323231, 243.25203...",comparison/metrabs_rn152_y4_bs=8.txt
20,rn152,y4,16,54.83,75.51,361.810446,376.255055,23.515941,"[361.810446, 418.217659, 380.878925, 371.01221...",comparison/metrabs_rn152_y4_bs=16.txt
54,rn152,y4,32,54.83,72.16,1059.790611,694.709659,21.709677,"[1059.790611, 693.585873, 670.631647, 672.3444...",comparison/metrabs_rn152_y4_bs=32.txt
7,rn18,y4,8,20.30,93.12,21005.985022,157.360633,19.670079,"[21005.985022, 146.368742, 157.152891, 178.003...",comparison/metrabs_rn18_y4_bs=8.txt
27,rn18,y4,16,20.30,73.78,246.417761,256.462216,16.028889,"[246.417761, 276.022434, 274.258137, 248.56090...",comparison/metrabs_rn18_y4_bs=16.txt
3,rn18,y4,32,20.24,80.91,531.647921,489.847462,15.307733,"[531.647921, 483.387232, 489.137173, 491.43791...",comparison/metrabs_rn18_y4_bs=32.txt
24,rn18,y4,64,20.24,91.20,1011.246681,1059.318304,16.551849,"[1011.246681, 1041.956902, 1011.490822, 1124.5...",comparison/metrabs_rn18_y4_bs=64.txt
17,rn18,y4,128,20.24,113.03,23795.506954,2535.790443,19.810863,"[23795.506954, 2535.790443]",comparison/metrabs_rn18_y4_bs=128.txt
6,rn34,y4,8,28.28,94.69,19514.328480,171.813578,21.476697,"[19514.32848, 188.21311, 196.802855, 193.57276...",comparison/metrabs_rn34_y4_bs=8.txt
53,rn34,y4,16,28.28,72.13,250.874281,270.237843,16.889865,"[250.874281, 302.519083, 246.645927, 261.53683...",comparison/metrabs_rn34_y4_bs=16.txt
22,rn34,y4,32,28.37,78.21,587.161064,526.362975,16.448843,"[587.161064, 514.702797, 527.020216, 524.73950...",comparison/metrabs_rn34_y4_bs=32.txt
26,rn34,y4,64,28.37,93.74,1143.857241,1150.367737,17.974496,"[1143.857241, 1144.272804, 1154.496431, 1152.3...",comparison/metrabs_rn34_y4_bs=64.txt
12,rn34,y4,128,28.37,112.30,21840.201616,2724.951744,21.288685,"[21840.201616, 2724.951744]",comparison/metrabs_rn34_y4_bs=128.txt
46,rn50,y4,8,35.58,89.12,23896.037817,179.182390,22.397799,"[23896.037817, 170.761347, 191.482544, 181.917...",comparison/metrabs_rn50_y4_bs=8.txt
49,rn50,y4,16,35.58,80.06,289.070845,299.343864,18.708992,"[289.070845, 323.168755, 349.534035, 276.86715...",comparison/metrabs_rn50_y4_bs=16.txt
42,rn50,y4,32,35.58,78.47,605.756044,567.364256,17.730133,"[605.756044, 569.657326, 572.298765, 548.75993...",comparison/metrabs_rn50_y4_bs=32.txt